### ISSUE TITLE
AOSP (Android) Version

### ISSUE THREAD

**Issue by EmanuelLoos** [sp4c38/AWattPrice#125]
I have no idea how difficult this might be, but if it does not require too much effort an AOSP version of the app would be great, I would especially like to see it on [F-Droid](https://f-droid.org/en/docs/FAQ_-_App_Developers/).

**Comment by sp4c38** [comment]
Thank you very much for the suggestion. That won't be possible at the moment. AWattPrice was created using Apple's SwiftUI native framework. There is currently no way to publish SwiftUI apps on Android. It would require a complete rewrite of the app and the maintenance of two separate code bases. That would greatly slow down development. If there is any possible way to port SwiftUI apps to Android in the future - which I very much doubt will happen - this can be considered again.

**Comment by EmanuelLoos** [comment]
@sp4c38 

There seems to be a way to compile SwiftUI Apps for Android:

https://skip.tools/

https://github.com/skiptools/skip-ui
